name: AUR
author: Minecraft AUR OpenSource Community
main: com.mcaur.bukkit.bootstrap.BukkitBootstrap
api-version: 1.13
version: 1.0.0

commands:
  aur:
    aliases:
      - aur
    description: Run this command to get AUR's help message.

permissions:
  "aur.command.help":
    description: Allow op can look AUR's help message.
  "aur.command.update":
    description: Make op can update plugin.
    default: op
  "aur.command.download":
    description: To get AUR plugin Hub plugin.
    default: op
  "aur.command.delete":
    description: Allow op to delete useless plugin and their folder.
    default: op
  "aur.command.checkupdate":
    description: Allow op can check plugin update.
    default: op
  "aur.command.version":
    description: Allow op can check AUR version and update AUR.
    default: op